USE master
USE yosubo;
GO
--CREACION DE LOGIN
CREATE LOGIN agustin with password='12345';
GO
CREATE USER Uagustin FOR LOGIN [agustin];

--CREACION DE USUARIO
CREATE LOGIN yamil with password='12345';
GO
CREATE USER Uyamil FOR LOGIN yamil;

--AÑADIMOS ROLES DE SOLO LECTURA Y DENEGAMOS LA ESCRITURA
ALTER ROLE db_denydatawriter ADD MEMBER Uyamil;
ALTER ROLE db_datareader ADD MEMBER Uyamil;

ALTER ROLE db_denydatawriter ADD MEMBER Uagustin;
ALTER ROLE db_datareader ADD MEMBER Uagustin;


--FUNCIONES Y PROCEDIMIENTOS
--PERMITIMOS UNICAMENTE ASIGNAR RESERVAS DESDE EL PROCEDIMIENTO
GRANT EXECUTE ON dbo.fnCrearReserva TO Uyamil;
GRANT EXECUTE ON dbo.fnCrearReserva TO Uagustin;
GRANT SELECT ON dbo.fnReservasPagadas TO Uyamil;
GRANT EXECUTE ON dbo.fnLugarDisponible TO Uyamil;
